keys:
  - &admin age1x2fvs92qtm7lw53kncs68n562cjak65z4hv23wjkrenprh6g5v4qgjdwz3
  - &watson age18yg47wkfu6dq27jrxajrazf8agvd93m0hfjlns9xac9422u4lduskyzhe5
  - &lestrade age1d332dljl362fxr4pjd2df0kx27a92j68qs2p3jjl44c9djtnef6s82trgv

creation_rules:
  - path_regex: ^secrets\.yaml$
    key_groups:
      - age:
          - *admin
          - *watson
          - *lestrade
